# Generated by Django 4.2.4 on 2023-10-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(default=False, verbose_name='took responsibility')),
                ('message', models.TextField()),
                ('person', models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50)),
                ('option', models.CharField(choices=[('My password does not worl', 'My password does not worl'), ('Update resume', 'Update resume'), ('Others', 'Others'), ('I lost my account', 'I lost my account')], max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True)),
            ],
        ),
    ]
