# Generated by Django 4.2.4 on 2023-10-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_message_alter_support_option_alter_support_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='situation',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Others', 'Others'), ('My password does not world', 'My password does not world'), ('I lost my account', 'I lost my account'), ('Update resume', 'Update resume')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True),
        ),
    ]
