# Generated by Django 4.2.4 on 2023-10-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_message_situation_alter_support_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='situation',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Others', 'Others'), ('Update resume', 'Update resume'), ('My password does not world', 'My password does not world'), ('I lost my account', 'I lost my account')], max_length=50),
        ),
    ]
