# Generated by Django 4.2.4 on 2023-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_notepad_alter_message_situation_alter_support_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('frontend', models.CharField(max_length=100)),
                ('backend', models.CharField(max_length=100)),
                ('fullstack', models.CharField(max_length=100)),
                ('intern', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='situation',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Update resume', 'Update resume'), ('Others', 'Others'), ('My password does not world', 'My password does not world'), ('I lost my account', 'I lost my account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='situation',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True),
        ),
    ]
