# Generated by Django 4.2.4 on 2023-10-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_vacancies_alter_message_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('My password does not world', 'My password does not world'), ('Others', 'Others'), ('I lost my account', 'I lost my account'), ('Update resume', 'Update resume')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True),
        ),
    ]
