# Generated by Django 4.2.4 on 2023-10-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_support_option_alter_support_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('I lost my account', 'I lost my account'), ('Update resume', 'Update resume'), ('My password does not world', 'My password does not world'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='situation',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True),
        ),
    ]
