# Generated by Django 4.2.4 on 2023-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_countdown_alter_message_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('My password does not world', 'My password does not world'), ('Others', 'Others'), ('I lost my account', 'I lost my account'), ('Update resume', 'Update resume')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50),
        ),
    ]
